# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 'Open Disclosure California: Static!'
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  An experiment rendering the Open Disclosure website as a static Jekyll site.
baseurl: "/odca-jekyll" # the subpath of your site, e.g. /blog
url: "https://adborden.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: adborden
github_username:  adborden
future: true

# TODO: allow this to be customized, or bake this into the main backend repo
odca_build_path: "~/dev/ruby/disclosure-backend-static/build"

defaults:
  - scope:
      type: ballot
    values:
      layout: ballot
  - scope:
      type: candidate
    values:
      layout: candidate
  - scope:
      type: locality
    values:
      layout: locality
  - scope:
      type: referendum
    values:
      layout: referendum

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - locality/oakland.html

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
